//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HostelModelContainer : DbContext
    {
        public HostelModelContainer()
            : base("name=HostelModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Hostel> HostelSet { get; set; }
        public virtual DbSet<Room> RoomSet { get; set; }
        public virtual DbSet<Student> StudentSet { get; set; }
        public virtual DbSet<Person> PersonSet { get; set; }
        public virtual DbSet<Faculty> FacultySet { get; set; }
        public virtual DbSet<Group> GroupSet { get; set; }
        public virtual DbSet<Ocupation> OcupationSet { get; set; }
        public virtual DbSet<Order> OrderSet { get; set; }
        public virtual DbSet<Payment> PaymentSet { get; set; }
    }
}
