//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public double Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
    
        public virtual Person Payer { get; set; }
        public virtual Order Order { get; set; }
    }
}
